---
services:
  db:
    image: manisha03b/pythonapp:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1

  auth-service:
    image: manisha03b/pythonapp:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    depends_on:
      - db

  book-service:
    image: manisha03b/pythonapp:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
    depends_on:
      - db

  borrow-service:
    image: manisha03b/pythonapp:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
    depends_on:
      - db

  frontend:
    image: manisha03b/pythonapp:appimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
    depends_on:
      - auth-service
      - book-service
      - borrow-service
